import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";


export const metadata: Metadata = {
  title: "Jayvee Maniquiz - Web Developer",
  description: "Generated by create next app",
    icons: {
    icon: "/image/Profile.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="inter">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}

          <footer className="container mx-auto max-w-[50rem] min-h-[5rem] flex justify-center items-center border  border-t-gray-300 border-l-0 border-r-0 px-2 md:px-0 mt-3">
            <p className="text-[0.8rem]">
              maniquizjayvee.business@gmail.com
            </p>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}

